# ── Camunda SaaS Cluster ─────────────────────────────────────────────
zeebe.client.cloud.cluster-id=09e23dc2-c664-4aeb-9297-127895dc0a9f
zeebe.client.cloud.client-id=ZM56aM4z5t9eH3q14x34fIvi.jNyT0Dh
zeebe.client.cloud.client-secret=hPG7A9E4dkh31ucpOwYTsk6zZmxlNXGjA2_Lt0rJpwPgHG4A1SjuCLt5Sf_cVQQc
zeebe.client.cloud.region=cle-1

# ── Spring Boot ───────────────────────────────────────────────────────
server.port=8080
spring.application.name=usine-client

# ── Logging ───────────────────────────────────────────────────────────
logging.level.io.camunda=INFO
logging.level.com.textile=DEBUG
