# ?? Camunda SaaS Cluster ?????????????????????????????????????????????
zeebe.client.cloud.cluster-id=
zeebe.client.cloud.client-id=
zeebe.client.cloud.client-secret=
zeebe.client.cloud.region=cle-1

# ?? Spring Boot ???????????????????????????????????????????????????????
server.port=8081
spring.application.name=fournisseur-client

# ?? Logging ???????????????????????????????????????????????????????????
logging.level.io.camunda=INFO
logging.level.com.textile=DEBUG

# Disable gRPC streaming to avoid 502 errors
zeebe.client.worker.stream-enabled=false
zeebe.client.worker.default-job-worker-stream-enabled=false
